openapi: 3.0.0
info:
  title: AWS Certification Assistant API
  version: 1.0.0
  description: APIs for fetching AWS Cloud Practitioner study resources
paths:
  /study:
    get:
      summary: Get a study resource from AWS
      description: Retrieve a study resource for the AWS Cloud Practitioner exam. Only use this when explicitly asked
      operationId: getStudyResource
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                topicSearch:
                  type: string
                  description: A search string describing the AWS certification topic to look for.
              required:
                - topicSearch
      responses:
        '200':
          description: Retrieve a study resource from AWS. Only use this when explicitly asked
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    url:
                      type: string
                      description: The URL of the study material.
                    title:
                      type: string
                      description: The title of the study resource.
                    summary:
                      type: string
                      description: A short summary of the resource
